### ISSUE TITLE
Error: access_denied, Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)

### ISSUE THREAD

**Issue by shang271828** [zhile-io/ChatGPTAuthHelper#10]
Error: access_denied, Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)

有人遇到这个问题吗？之前都是正常的，从今天开始有这个报错。
重新安装了也没用。
求解答。

**Comment by shan163168** [comment]
同样遇到这个问题
