### ISSUE TITLE
Error: access_denied, Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)

### ISSUE THREAD

**Issue by tangjiahao2001** [zhile-io/ChatGPTAuthHelper#11]

**Comment by pankejia2000** [comment]
是的！我也显示这个。Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.。。但是我已经升级到最新的 版本1.1.3

**Comment by AppleJack-eng** [comment]
一样的

**Comment by i-yuanfang** [comment]
我也遇到同样问题，登录官方chatgpt ，然后 https://chat.openai.com/api/auth/session 这里获取，亲测有效
