### ISSUE TITLE
使用了1.1.3版本的扩展，依然提示如下错误，无法获取token

### ISSUE THREAD

**Issue by truelv** [zhile-io/ChatGPTAuthHelper#14]
![image](https://github.com/zhile-io/ChatGPTAuthHelper/assets/13477144/2a529e41-016c-4b97-a750-2ebecb723e23)

而且最新版本扩展内的manifest.json里的version还是1.1.2，我改成了1.1.3依然报错

**Comment by tomhup** [comment]
同样的报错

**Comment by tomhup** [comment]
https://chat.openai.com/api/auth/session    用这个地址可以

**Comment by ptisnoob** [comment]
same issue

**Comment by li-Coulson** [comment]
same issue

**Comment by ptisnoob** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AppleJack-eng** [comment]
同样的问题

**Comment by CrazyBunQnQ** [comment]
> https://chat.openai.com/api/auth/session 用这个地址可以

可以了！感谢！

**Comment by Jasone1-3** [comment]
> https://chat.openai.com/api/auth/session 用这个地址可以

ok感谢老哥，有没有能长期储存key的文件操作啊，经常弄好麻烦

**Comment by 3038922** [comment]
我也是.你们上面用的那个我用不了.

**Comment by zhile-io** [comment]
> 我也是.你们上面用的那个我用不了.

https://ai.fakeopen.com/auth1 试试

**Comment by SLAAASHH** [comment]
> > 我也是.你们上面用的那个我用不了.
> 
> https://ai.fakeopen.com/auth1 试试

这个地址点击后的页面是一堆英文和数字

**Comment by huajie19890** [comment]
> > 我也是.你们上面用的那个我用不了.
> 
> https://ai.fakeopen.com/auth1 试试
之前是使用的谷歌邮箱登录的，现在这个页面上输入提示如下：
获取失败: access_denied: You tried signing in as "xxxxxxxxx@gmail.com" using a password, which is not the authentication method you used during sign up. Try again using the authentication method you used during sign up. (error=identity_provider_mismatch)

**Comment by BrowserZz** [comment]
使用谷歌第三方登录，还是报错，有成功的吗？
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by BrowserZz** [comment]
> 使用谷歌第三方登录，还是报错，有成功的吗？ Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

先登录上官网，再访问 https://chat.openai.com/api/auth/session 就能拿到access token了

**Comment by Shinkai007** [comment]
> > 使用谷歌第三方登录，还是报错，有成功的吗？ Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.
> 
> 先登录上官网，再访问 https://chat.openai.com/api/auth/session 就能拿到access token了

确定这个可以了. 先用第三方谷歌账号登录上chat官网, 再刷新进入上面链接即可.

**Comment by freemankevin** [comment]
`Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.`

same error.

**Comment by freemankevin** [comment]
It's work. Thanks a lot.
