### ISSUE TITLE
现在/auth/preauth接口没有cookie返回了

### ISSUE THREAD

**Issue by LaiBaoYuan** [zhile-io/ChatGPTAuthHelper#15]
<img width="561" alt="image" src="https://github.com/zhile-io/ChatGPTAuthHelper/assets/89441249/21d72e8a-c777-4c2e-866a-3f21d36f7140">

**Comment by zhile-io** [comment]
此方式不再适用

**Comment by LaiBaoYuan** [comment]
大佬，想问问，如果这种方式失效了，现在是不是没有方法可以用代码的方式完成谷歌accesstoken的自动化获取呀？是不是只能通过网页点击选择账号的方式跳转到`https://ai.fakeopen.com/auth`这里才能获取
