### ISSUE TITLE
跟大家出现版本过期登陆不上chant后，将插件卸载重装，扩展安装又显示“清单找不到或无法获取”，求大佬支招这怎么回事

### ISSUE THREAD

**Issue by jiangdoubao** [zhile-io/ChatGPTAuthHelper#19]

**Comment by hirealkevin** [comment]
打开 chrome://flags/#extensions-on-chrome-urls 将 Extensions on edge:// URLs 的 Disabled 改为 Enabled，重启浏览器。
然后在浏览器扩展页面 chrome://extensions/ 开启开发者模式，直接拖入 .crx 扩展文件即可安装成功。

**Comment by jiangdoubao** [comment]
感谢解决了

**Comment by sjhsbhqf** [comment]
大家下载压缩包后，加载那个src目录，而不是顶级目录
