### ISSUE TITLE
Cannot load plugin "Manifest version 2 is deprecated"

### ISSUE THREAD

**Issue by kanrin** [zhile-io/ChatGPTAuthHelper#20]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

是不是考虑升级到manifest 3?

**Comment by f0ghua** [comment]
Thanks for the project, it helps me much. I meet the same issue and have udpated the manifest file for v3. Just for your reference

```diff
diff -urN ChatGPTAuthHelper-1.2.0.org/src/background.js ChatGPTAuthHelper-1.2.0/src/background.js
--- ChatGPTAuthHelper-1.2.0.org/src/background.js	2023-10-30 17:58:10.000000000 +0800
+++ ChatGPTAuthHelper-1.2.0/src/background.js	2023-11-01 16:38:11.973896500 +0800
@@ -1,4 +1,4 @@
-chrome.browserAction.onClicked.addListener(function (tab) {
+chrome.action.onClicked.addListener(function (tab) {
     chrome.tabs.create({url: 'https://ai-' + yesterday() + '.fakeopen.com/auth'});
 });
 
diff -urN ChatGPTAuthHelper-1.2.0.org/src/manifest.json ChatGPTAuthHelper-1.2.0/src/manifest.json
--- ChatGPTAuthHelper-1.2.0.org/src/manifest.json	2023-10-30 17:58:10.000000000 +0800
+++ ChatGPTAuthHelper-1.2.0/src/manifest.json	2023-11-02 09:53:47.146724600 +0800
@@ -1,5 +1,5 @@
 {
-  "manifest_version": 2,
+  "manifest_version": 3,
   "name": "ChatGPT Auth Helper",
   "version": "1.2.0",
   "description": "A simple Chrome extension to help you login ChatGPT.",
@@ -7,26 +7,24 @@
   "homepage_url": "https://github.com/zhile-io/ChatGPTAuthHelper",
   "permissions": [
     "tabs",
-    "<all_urls>",
     "webRequest",
-    "webRequestBlocking",
     "storage"
   ],
-  "browser_action": {
+  "host_permissions": [
+    "<all_urls>"
+  ],
+  "action": {
     "default_icon": "icon.png",
     "default_title": "点击打开ChatGPT Auth服务"
   },
   "background": {
-    "scripts": [
-      "background.js"
-    ],
-    "persistent": true
+	"service_worker": "background.js"
   },
-  "web_accessible_resources": [
-    "auth.html",
-    "auth.js",
-    "assets/**"
-  ],
+  "web_accessible_resources": [{
+    "resources": ["auth.html", "auth.js", "assets/**"],
+    "matches": [],
+    "extension_ids": []
+  }],
   "content_scripts": [
     {
       "matches": [

```

**Comment by zhile-io** [comment]
> Thanks for the project, it helps me much. I meet the same issue and have udpated the manifest file for v3. Just for your reference
> 
> ```diff
> diff -urN ChatGPTAuthHelper-1.2.0.org/src/background.js ChatGPTAuthHelper-1.2.0/src/background.js
> --- ChatGPTAuthHelper-1.2.0.org/src/background.js	2023-10-30 17:58:10.000000000 +0800
> +++ ChatGPTAuthHelper-1.2.0/src/background.js	2023-11-01 16:38:11.973896500 +0800
> @@ -1,4 +1,4 @@
> -chrome.browserAction.onClicked.addListener(function (tab) {
> +chrome.action.onClicked.addListener(function (tab) {
>      chrome.tabs.create({url: 'https://ai-' + yesterday() + '.fakeopen.com/auth'});
>  });
>  
> diff -urN ChatGPTAuthHelper-1.2.0.org/src/manifest.json ChatGPTAuthHelper-1.2.0/src/manifest.json
> --- ChatGPTAuthHelper-1.2.0.org/src/manifest.json	2023-10-30 17:58:10.000000000 +0800
> +++ ChatGPTAuthHelper-1.2.0/src/manifest.json	2023-11-02 09:53:47.146724600 +0800
> @@ -1,5 +1,5 @@
>  {
> -  "manifest_version": 2,
> +  "manifest_version": 3,
>    "name": "ChatGPT Auth Helper",
>    "version": "1.2.0",
>    "description": "A simple Chrome extension to help you login ChatGPT.",
> @@ -7,26 +7,24 @@
>    "homepage_url": "https://github.com/zhile-io/ChatGPTAuthHelper",
>    "permissions": [
>      "tabs",
> -    "<all_urls>",
>      "webRequest",
> -    "webRequestBlocking",
>      "storage"
>    ],
> -  "browser_action": {
> +  "host_permissions": [
> +    "<all_urls>"
> +  ],
> +  "action": {
>      "default_icon": "icon.png",
>      "default_title": "点击打开ChatGPT Auth服务"
>    },
>    "background": {
> -    "scripts": [
> -      "background.js"
> -    ],
> -    "persistent": true
> +	"service_worker": "background.js"
>    },
> -  "web_accessible_resources": [
> -    "auth.html",
> -    "auth.js",
> -    "assets/**"
> -  ],
> +  "web_accessible_resources": [{
> +    "resources": ["auth.html", "auth.js", "assets/**"],
> +    "matches": [],
> +    "extension_ids": []
> +  }],
>    "content_scripts": [
>      {
>        "matches": [
> ```

Thank you very much for your help. I have already upgraded it.
