### ISSUE TITLE
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

### ISSUE THREAD

**Issue by jiupinjiandingshi** [zhile-io/ChatGPTAuthHelper#7]
它说版本不对哇

**Comment by freemankevin** [comment]
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by ettingshausen** [comment]
+1

**Comment by cowboy1975** [comment]
+1

**Comment by imok7** [comment]
+1. 
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by superleo-cn** [comment]
有人解决了吗？

**Comment by chgy188** [comment]
+1

**Comment by freemankevin** [comment]
Try the new version, it should work.

**Comment by huajie19890** [comment]
+1

**Comment by huajie19890** [comment]
> Try the new version, it should work.

which version is ok ?

**Comment by freemankevin** [comment]
Yes，it is work.
See this issue [ https://github.com/zhile-io/ChatGPTAuthHelper/issues/14]( https://github.com/zhile-io/ChatGPTAuthHelper/issues/14)
